### ISSUE TITLE
共建electron-toolkit

### ISSUE THREAD

**Issue by chenfq95** [alex8088/electron-toolkit#1]
### Clear and concise description of the problem

我开发了一个适用于electron主进程的IOC 服务治理管理小工具，想发布在@electron-toolkit这个npm 组织下，不知道是否可以，这个是我的代码仓库：https://github.com/heychenfq/electron-toolkit
不知道怎么联系您，只能在仓库里提交issue了。

### Suggested solution

not yet

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-toolkit/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-toolkit/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://github.com/alex8088/electron-toolkit#readme).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-toolkit/issues) that reports the same bug to avoid creating a duplicate.

**Comment by chenfq95** [comment]
望回复，这个是我的微信号：heychenfq，后面有机会一起交流electron相关技术栈呀

**Comment by trasherdk** [comment]
Repository name collision, and name not matching the package name.

**Comment by chenfq95** [comment]
wait for the auchor reply, I will change package name in my repo!

**Comment by alex8088** [comment]
hi， @heychenfq 很抱歉现在才回复。electron-toolkit 本意在monorepo下管理，统一规范，子包也有依存关系。如果分属不同仓库，这不利于规范和问题反馈，使用者会混淆。如果electron-toolkit是一个github组织那没问题，但不是，所以不推荐这样的做法。我也仔细研读了你代码，非常棒，想法很好，值得学习。我建议你采用一级命名如electorn-ioc，更有利于你的开源分享推广。
