### ISSUE TITLE
ipcRenderer.removeListener不生效

### ISSUE THREAD

**Issue by zhangmingming3** [alex8088/electron-toolkit#10]
### Describe the bug

主进程：
    setInterval(() => {
        mainWindow.webContents.send("sendMessage", {id: 1, type: 4})
    }, 5000);
渲染进程，vue组件
onMounted(()=>{
    window.electron.ipcRenderer.on('sendMessage',getMessage)
})
onBeforeUnmount(()=>{
    window.electron.ipcRenderer.removeListener('sendMessage',getMessage)
})
 const getMessage=(val,message)=>{
    console.log(val);
    console.log(message);
}
组件销毁后，依旧能接收消息并在控制台打印，频繁创建销毁该组件，打印次数会累加

### Electron-Toolkit Version

3.0.0

### Electron Version

28.2.0

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-toolkit/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-toolkit/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://github.com/alex8088/electron-toolkit#readme).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-toolkit/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
@zhangmingming3 https://github.com/alex8088/electron-toolkit/tree/master/packages/preload#get-started

**Comment by zhangmingming3** [comment]
还是不理解为什么electron.ipcRenderer.removeListener('sendMessage',getMessage)不生效；但removeAllListeners是生效的。

**Comment by alex8088** [comment]
因为 preload 在数据传递时会进行序列化和反序列化，绑定的函数即getMessage并不是同一个对象，所以这种移除方式是不成功的，使用返回的removeListener函数去preload中移除监听，即移除真正的绑定的函数getMessage

https://www.electronjs.org/zh/docs/latest/api/context-bridge#api-functions

**Comment by alex8088** [comment]
removeAllListeners，则无需理会绑定的函数，则能够成功

**Comment by alex8088** [comment]
简单理解就是preload和renderer的进程内存不共享
