### ISSUE TITLE
Undefined Electron API's

### ISSUE THREAD

**Issue by lynxionxs** [alex8088/electron-toolkit#11]
### Describe the bug

Why is there only 3 electron api's available with ```import { electronAPI } from '@electron-toolkit/preload'``` ?
```process, ipcRenderer, webFrame```.
Example : I want to use the api for ```app``` to get the data path ```app.getPath('appData')``` . 
Importing ```app``` in ```../preload/index.ts``` ```import { app, contextBridge } from 'electron'``` shows ```app``` as ```undefined```. 
Now how am i supposed to get access to those other electron api's ?

### Electron-Toolkit Version

3.0.0

### Electron Version

28.2.0

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-toolkit/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-toolkit/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://github.com/alex8088/electron-toolkit#readme).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-toolkit/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
`app` cannot be used in preload/renderer. You should use ipc to handle.

**Comment by lynxionxs** [comment]
@alex8088  How to use ipc to handle ? All i want is to get the ```app.getPath('appData')```
Can you give example using IPC ?

**Comment by alex8088** [comment]
https://github.com/alex8088/EvPlayer

**Comment by lynxionxs** [comment]
@alex8088  Thanks. Is it okay to use the ipcRenderer from electron in the preload script, or must i use the ipcRenderer from ```electronAPI``` in preload script ?

```js
../preload/index.ts

import { contextBridge, ipcRenderer } from 'electron'
import { electronAPI } from '@electron-toolkit/preload'

// Custom APIs for renderer
const api = {
  getAppDataPath: () => ipcRenderer.invoke('get-appData-path')
}

if (process.contextIsolated) {
  try {
    contextBridge.exposeInMainWorld('electron', electronAPI)
    contextBridge.exposeInMainWorld('api', api)
  } catch (error) {
    console.error(error)
  }
} else {
  // @ts-ignore (define in dts)
  window.electron = electronAPI
  // @ts-ignore (define in dts)
  window.api = api
}
```

**Comment by alex8088** [comment]
https://github.com/alex8088/electron-toolkit/tree/master/packages/preload#get-started
