### ISSUE TITLE
关于 electron-toolkit/tsconfig 中 moduleResolution 配置问题

### ISSUE THREAD

**Issue by mice33** [alex8088/electron-toolkit#15]
### Describe the bug

基于 @quick-start/electron 创建一个 vue + ts 项目，并且安装了 electron-store 版本 "^10.0.0"。
在项目中使用 electron-store 时，TypeScript 报错：
```
src/main/index.ts:8:7 - error TS2339: Property 'set' does not exist on type 'ElectronStore<Record<string, unknown>>'.

8 store.set('foo', 'bar')
``` 
根据 https://github.com/sindresorhus/electron-store/issues/276 中 [sindresorhus](https://github.com/sindresorhus) 提供的解决方案, 可解决此问题

在 tsconfig.web.json 和 tsconfig.node.json 中 `compilerOptions` 添加如下配置
```
"module": "NodeNext",
"moduleResolution": "NodeNext"
```

package.json 需要添加
```
"type": "module"
```

求助：
我的问题是，是否需要按照 sindresorhus 的解决方案来解决此问题？如果需要这么做的话，是否需要在 electron-toolkit/tsconfig 中统一更改 moduleResolution 配置？

问题项目相关链接：https://github.com/mice33/tsconfig

### Electron-Toolkit Version

1.0.1

### Electron Version

28.3.3

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-toolkit/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-toolkit/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://github.com/alex8088/electron-toolkit#readme).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-toolkit/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
@mice33 理解 [sindresorhus](https://github.com/sindresorhus) 大神对 ESM 的推崇。但由于 Electron 的历史原因，并不是所有版本都支持 ESM，这种强制转换并且必须是node 20及以上要求，给很多Electorn开发者造成了一定的负担。我认为只支持 ESM 也没有问题，只需要导出 electron-store 的底层 Conf 的类型即可，看issue的相关提议也没有被接受。实际这也都没有问题按给出的方案，也可以解决问题，前提是你决定将项目迁移到ESM。这个可以看 electron-vite 文档[相关内容]( https://cn.electron-vite.org/guide/dev#electron-%E7%9A%84-esm-%E6%94%AF%E6%8C%81)，基本无需更改什么，electron-vite 做了一定的兼容处理。

就目前而言，不太好强制electron开发者选择esm，默认tsconfig还是要为绝大多数开发者考虑。有需要的同学自行配置就好。

此外，我推荐你使用更好用的 [ electron-conf ](https://github.com/alex8088/electron-conf) 无缝切换
