### ISSUE TITLE
The typed IpcListener method .on should allow unsubscribing from the event

### ISSUE THREAD

**Issue by davbrito** [alex8088/electron-toolkit#18]
### Describe the bug

I can't unsubscribe from a typed-ipc IpcListener event.

It does not return the callback from `.on()`:

https://github.com/alex8088/electron-toolkit/blob/554c21d49c6620c1e32a39572cb5894e25e4262b/packages/typed-ipc/src/renderer.ts#L26-L31

Which is defined here:
https://github.com/alex8088/electron-toolkit/blob/554c21d49c6620c1e32a39572cb5894e25e4262b/packages/preload/src/index.ts#L32-L37

### Electron-Toolkit Version

@electron-toolkit/typed-ipc@1.0.1, @electron-toolkit/preload@3.0.1

### Electron Version

electron@33.0.1

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-toolkit/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-toolkit/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://github.com/alex8088/electron-toolkit#readme).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-toolkit/issues) that reports the same bug to avoid creating a duplicate.

**Comment by davbrito** [comment]
I did this as a workaround:
![image](https://github.com/user-attachments/assets/079f3a42-dd4c-4636-9b8a-b47bbd1ee2d6)

**Comment by alex8088** [comment]
new ver is out 🎉 ! Fixed.
