### ISSUE TITLE
Can't using sendSync (@electron-toolkit/preload)

### ISSUE THREAD

**Issue by tranhuuloc2010** [alex8088/electron-toolkit#3]
### Describe the bug

I can't using sendSync on App.vue but send and on it ok.
const data = await window.electron.ipcRenderer.sendSync('chanel', 'value')
data always return undefined.
I think it is a  bug

### Electron-Toolkit Version

^1.0.2

### Electron Version

^21.3.0

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-toolkit/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-toolkit/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://github.com/alex8088/electron-toolkit#readme).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-toolkit/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
@tranhuuloc2010, You've got it. I'll fix it soon.

**Comment by alex8088** [comment]
ver `1.0.3` is out

**Comment by tranhuuloc2010** [comment]
It worked!

> ver `1.0.3` is out
