### ISSUE TITLE
escToCloseWindow is Not work

### ISSUE THREAD

**Issue by Ezio1212** [alex8088/electron-toolkit#4]
### Describe the bug

in function optimizer.watchWindowShortcuts.
2nd parameter's property escToCloseWindow is Not work.

the code just read `window.close` property, but not run it.

in code https://github.com/alex8088/electron-toolkit/blob/master/packages/utils/src/optimizer.ts#L68

```
 if (escToCloseWindow) {
          if (input.code === 'Escape' && input.key !== 'Process') {
            window.close    // <-- HERE!
            event.preventDefault()
          }
        }
```

### Electron-Toolkit Version

latest

### Electron Version

any

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-toolkit/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-toolkit/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://github.com/alex8088/electron-toolkit#readme).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-toolkit/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
You found a bug, I will fix it soon. 🤝

**Comment by alex8088** [comment]
@electron-toolkit/utils 2.0.1 is out!
