### ISSUE TITLE
ipcRenderer.postMessage should throw error when contextIsolated is enabled

### ISSUE THREAD

**Issue by wong2** [alex8088/electron-toolkit#5]
### Describe the bug

It wasted me hours figuring out why `ipcRenderer.postMessage` has no effect at all. 😂
Then I read the source code and found out if `contextIsolated` is enabled, the function just returns silently, which I believe is a bad practice.

https://github.com/alex8088/electron-toolkit/blob/84807b969cf785a35fa696cbedc8ba829a1fea14/packages/preload/src/index.ts#L20

### Electron-Toolkit Version

2.0.0

### Electron Version

25.6.0

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-toolkit/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-toolkit/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://github.com/alex8088/electron-toolkit#readme).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-toolkit/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
preload@3.0.0 is out!
