### ISSUE TITLE
CommandOrControl + Shift + R still works on production when using optimizer from @electron-toolkit/utils

### ISSUE THREAD

**Issue by xreq403** [alex8088/electron-toolkit#6]
### Describe the bug

I use optimzer from @electron-toolkit/utils

It only ignores  CommandOrControl + R, but when I press CommandOrControl + Shift + R it still reloads the page.

```
  // Default open or close DevTools by F12 in development
  // and ignore CommandOrControl + R in production.
  // see https://github.com/alex8088/electron-toolkit/tree/master/packages/utils
  app.on('browser-window-created', (_, window) => {
    optimizer.watchWindowShortcuts(window)
  })
```

How can I avoid  CommandOrControl + Shift + R?

### Electron-Toolkit Version

^2.0.1

### Electron Version

27.0.1

### Validations

- [X] Follow the [Code of Conduct](https://github.com/alex8088/electron-toolkit/blob/master/CODE_OF_CONDUCT.md).
- [X] Read the [Contributing Guidelines](https://github.com/alex8088/electron-toolkit/blob/master/CONTRIBUTING.md).
- [X] Read the [docs](https://github.com/alex8088/electron-toolkit#readme).
- [X] Check that there isn't [already an issue](https://github.com/alex8088/electron-toolkit/issues) that reports the same bug to avoid creating a duplicate.

**Comment by alex8088** [comment]
utils@3.0.0 is out!
